// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrf7viQm8UGbtiqcAj2PsZRU7ikIN8v7E',
    appId: '1:894168498081:web:3982dabfa9c72f7b56d5e0',
    messagingSenderId: '894168498081',
    projectId: 'rafli-bank-app',
    authDomain: 'rafli-bank-app.firebaseapp.com',
    storageBucket: 'rafli-bank-app.firebasestorage.app',
    measurementId: 'G-FJZQG6V3ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1eyly5QmcKdFuWEGTWE7rrLt7eMFOXM',
    appId: '1:894168498081:android:dfaf547f15f5caee56d5e0',
    messagingSenderId: '894168498081',
    projectId: 'rafli-bank-app',
    storageBucket: 'rafli-bank-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjhqLSCE30GffZOpHw2gMy8KZacIc-DUM',
    appId: '1:894168498081:ios:af07865977d8e83956d5e0',
    messagingSenderId: '894168498081',
    projectId: 'rafli-bank-app',
    storageBucket: 'rafli-bank-app.firebasestorage.app',
    iosBundleId: 'com.rafli.bank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjhqLSCE30GffZOpHw2gMy8KZacIc-DUM',
    appId: '1:894168498081:ios:af07865977d8e83956d5e0',
    messagingSenderId: '894168498081',
    projectId: 'rafli-bank-app',
    storageBucket: 'rafli-bank-app.firebasestorage.app',
    iosBundleId: 'com.rafli.bank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrf7viQm8UGbtiqcAj2PsZRU7ikIN8v7E',
    appId: '1:894168498081:web:82311385d06e44a256d5e0',
    messagingSenderId: '894168498081',
    projectId: 'rafli-bank-app',
    authDomain: 'rafli-bank-app.firebaseapp.com',
    storageBucket: 'rafli-bank-app.firebasestorage.app',
    measurementId: 'G-ME04BRHE4H',
  );

}